package SumaApp;


/**
* SumaApp/sumaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sumaApp.idl
* miércoles 29 de agosto de 2018 08:47:07 PM COT
*/

public interface sumaOperations 
{
  int sumar (int numero1, int numero2);
  void shutdown ();
} // interface sumaOperations
